name: hedon_haven
description: "Hedon Haven"
publish_to: 'none'
version: 0.6.7+2210
environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  html: ^0.15.6
  shared_preferences: ^2.5.5
  fvp: ^0.38.1
  video_player: ^2.14.0
  audio_video_progress_bar: ^2.0.3
  auto_orientation_v2: #^2.4.5
    git:
      url: https://github.com/Hedon-dev/auto_orientation_v2
      ref: patch-1
  window_manager: ^0.5.2
  flutter_hls_parser: ^2.0.1
  url_launcher: ^6.3.2
  dynamic_color: ^2.1.0
  wakelock_plus: ^1.7.0
  package_info_plus: ^10.2.1
  connectivity_plus: ^7.1.1
  skeletonizer: ^2.1.3
  sqflite_common_ffi: ^2.4.2+1
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.6
  toastification: ^3.2.0
  system_info2: ^4.1.0
  package_installer_plus: ^1.0.0
  dynamic_app_icon_flutter_plus: ^2.2.1
  yaml: ^3.1.3
  logger: ^2.7.0
  archive: ^4.2.0
  file_picker: ^12.0.0
  image: ^4.9.2
  crypto: ^3.0.7
  share_plus: ^13.3.0
  html_unescape: ^2.0.0
  linkify: ^5.0.0
  secure_app_switcher: ^1.0.0
  page_transition: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.3
  flutter_js: ^0.8.7
  animations: ^3.0.0
  path: ^1.9.1
  synchronized: ^3.4.1+2
  super_drag_and_drop: ^0.10.0-dev.2
  receive_sharing_intent: ^1.9.0
  rhttp: ^0.18.0
  material_ui: ^1.0.1
  perfect_volume_control: ^1.0.6
  showcaseview: ^5.1.0

# override to avoid error: Value of type 'NWPath' has no member 'isUltraConstrained'
dependency_overrides:
  connectivity_plus: 7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.8.1
  build_runner: ^2.16.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/launcher-icon/stock.png
    - assets/launcher-icon/stock_debug.png
    - assets/launcher-icon/fake_settings.png
    - assets/launcher-icon/fake_settings_debug.png
    - assets/launcher-icon/reminders.png
    - assets/launcher-icon/reminders_debug.png
